--1
DESC emp;

--2
SELECT *
FROM EMP
WHERE deptno = 30 AND job = 'SALESMAN';

--3
SELECT *
FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

--4
CREATE TABLE EMP_TEMP
AS
SELECT * FROM EMP WHERE 1 != 1;

SELECT * FROM EMP_TEMP;

--5
INSERT INTO emp_temp(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'홍길동','PRESIDENT',NULL,'01/01/01',5000,1000,10);

--6
CREATE TABLE DEPT_TEMP2
AS
SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

--7
UPDATE dept_temp2
SET DNAME = 'DATABASE' ,LOC = 'SEOUL'
WHERE DEPTNO = 40;

--8
ROLLBACK;

--9
SELECT *
FROM EMP
WHERE UPPER(ENAME) = 'SMITH';

--10
SELECT *
FROM EMP
WHERE LENGTH(ENAME) <=4;

--11
SELECT SUBSTR(JOB,1,3)
FROM EMP;

--12
SELECT *
FROM EMP
WHERE hiredate > '81/06/01';

--13
SELECT empno,ename,sal,NVL(comm,0), sal*12+ NVL(COMM,0) ANNSAL
FROM EMP;

--14
SELECT COUNT(DISTINCT JOB)
FROM EMP;

--15
SELECT e.ename 사원이름,d.dname 부서이름
FROM EMP e JOIN dept d ON e.deptno = d.deptno
WHERE SAL >= 3000;

--16
SELECT *
FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE ename='MARTIN');

--17
SELECT *
FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE deptno=30);

--18
SELECT *
FROM EMP e JOIN SALGRADE s ON SAL BETWEEN LOSAL AND HISAL
WHERE s.grade = 3 AND e.deptno =30;

--19
CREATE TABLE EMP_DDL (
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE    DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
);

DESC EMP_DDL;


--20
CREATE VIEW EMP_V3(직원번호,이름,직업,고용일자,월급,부서번호)
AS
SELECT EMPNO,ENAME,JOB,HIREDATE,SAL,DEPTNO FROM EMP;
SELECT * FROM EMP_V3;